# Generated by Django 4.1.3 on 2022-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_board_user_alter_card_list_alter_list_board"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["-last_access"]},
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="list",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
