# Generated by Django 4.1.3 on 2022-11-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_board_options_alter_card_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={},
        ),
    ]
