# Generated by Django 4.1.3 on 2022-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_card_order_remove_list_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["index"]},
        ),
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="card",
            name="index",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="list",
            name="index",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
