name: Apollo CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8
    - name: Run Tests
      run: |
        pip install coverage
        coverage run -m pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
    - name: Coverage Report
      run: |
        coverage report --fail-under=100

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
